// <auto-generated />
using System;
using LevelUp.Infra.Data.AppData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace LevelUp.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251111221917_IntialTables")]
    partial class IntialTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LevelUp.Domain.Entities.RewardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("reward_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("name");

                    b.Property<int>("PointCost")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("point_cost");

                    b.Property<int>("StockQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("stock_quantity");

                    b.HasKey("Id");

                    b.ToTable("TB_LEVELUP_REWARDS");
                });

            modelBuilder.Entity("LevelUp.Domain.Entities.RewardRedemptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("redemption_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PointsSpent")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("points_spent");

                    b.Property<DateTime>("RedeemedAt")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("redeemed_at");

                    b.Property<int>("RewardId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("reward_id");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.HasIndex("UserId");

                    b.ToTable("TB_LEVELUP_REWARD_REDEMPTIONS");
                });

            modelBuilder.Entity("LevelUp.Domain.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("team_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("team_name");

                    b.HasKey("Id");

                    b.HasIndex("TeamName")
                        .IsUnique();

                    b.ToTable("TB_LEVELUP_TEAMS");
                });

            modelBuilder.Entity("LevelUp.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("user_id");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("job_title");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("password_hash");

                    b.Property<int>("PointBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasDefaultValue(0)
                        .HasColumnName("point_balance");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasDefaultValue("USER")
                        .HasColumnName("role");

                    b.Property<int?>("TeamId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("TB_LEVELUP_USERS");
                });

            modelBuilder.Entity("LevelUp.Domain.Entities.RewardRedemptionEntity", b =>
                {
                    b.HasOne("LevelUp.Domain.Entities.RewardEntity", "Reward")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelUp.Domain.Entities.UserEntity", "User")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LevelUp.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("LevelUp.Domain.Entities.TeamEntity", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("LevelUp.Domain.Entities.RewardEntity", b =>
                {
                    b.Navigation("RewardRedemptions");
                });

            modelBuilder.Entity("LevelUp.Domain.Entities.TeamEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LevelUp.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("RewardRedemptions");
                });
#pragma warning restore 612, 618
        }
    }
}
